-- Generated By protoc-gen-lua Do not Edit
local protobuf = require( "depends/protobuf/protobuf" )
local __COMMON_ENUMS_PB = require( "pb/__common_enums_pb" )
local COMMON_BASE_PB = require( "pb/common_base_pb" )
--module('login_pb')
local login_pb = {}


local LOGINREQUEST = protobuf.Descriptor();
local LOGINREQUEST_USER_ID_FIELD = protobuf.FieldDescriptor();
local LOGINREQUEST_CHANNEL_UID_FIELD = protobuf.FieldDescriptor();
local LOGINRESPONSE = protobuf.Descriptor();
local LOGINRESPONSE_USER_ID_FIELD = protobuf.FieldDescriptor();
local LOGINRESPONSE_PLAYER_FIELD = protobuf.FieldDescriptor();
local CREATECHARACTERREQUEST = protobuf.Descriptor();
local CREATECHARACTERREQUEST_USER_ID_FIELD = protobuf.FieldDescriptor();
local CREATECHARACTERREQUEST_PLAYER_NAME_FIELD = protobuf.FieldDescriptor();
local CREATECHARACTERRESPONSE = protobuf.Descriptor();
local CREATECHARACTERRESPONSE_USER_ID_FIELD = protobuf.FieldDescriptor();
local LOGOUTRESPONSE = protobuf.Descriptor();
local LOGOUTRESPONSE_USER_ID_FIELD = protobuf.FieldDescriptor();
local HEARTBEAT = protobuf.Descriptor();
local HEARTBEAT_PLAYER_ID_FIELD = protobuf.FieldDescriptor();

LOGINREQUEST_USER_ID_FIELD.name = "user_id"
LOGINREQUEST_USER_ID_FIELD.full_name = ".my_project.LoginRequest.user_id"
LOGINREQUEST_USER_ID_FIELD.number = 1
LOGINREQUEST_USER_ID_FIELD.index = 0
LOGINREQUEST_USER_ID_FIELD.label = 2
LOGINREQUEST_USER_ID_FIELD.has_default_value = false
LOGINREQUEST_USER_ID_FIELD.default_value = 0
LOGINREQUEST_USER_ID_FIELD.type = 5
LOGINREQUEST_USER_ID_FIELD.cpp_type = 1

LOGINREQUEST_CHANNEL_UID_FIELD.name = "channel_uid"
LOGINREQUEST_CHANNEL_UID_FIELD.full_name = ".my_project.LoginRequest.channel_uid"
LOGINREQUEST_CHANNEL_UID_FIELD.number = 2
LOGINREQUEST_CHANNEL_UID_FIELD.index = 1
LOGINREQUEST_CHANNEL_UID_FIELD.label = 2
LOGINREQUEST_CHANNEL_UID_FIELD.has_default_value = false
LOGINREQUEST_CHANNEL_UID_FIELD.default_value = ""
LOGINREQUEST_CHANNEL_UID_FIELD.type = 9
LOGINREQUEST_CHANNEL_UID_FIELD.cpp_type = 9

LOGINREQUEST.name = "LoginRequest"
LOGINREQUEST.full_name = ".my_project.LoginRequest"
LOGINREQUEST.nested_types = {}
LOGINREQUEST.enum_types = {}
LOGINREQUEST.fields = {LOGINREQUEST_USER_ID_FIELD, LOGINREQUEST_CHANNEL_UID_FIELD}
LOGINREQUEST.is_extendable = false
LOGINREQUEST.extensions = {}
LOGINRESPONSE_USER_ID_FIELD.name = "user_id"
LOGINRESPONSE_USER_ID_FIELD.full_name = ".my_project.LoginResponse.user_id"
LOGINRESPONSE_USER_ID_FIELD.number = 1
LOGINRESPONSE_USER_ID_FIELD.index = 0
LOGINRESPONSE_USER_ID_FIELD.label = 2
LOGINRESPONSE_USER_ID_FIELD.has_default_value = false
LOGINRESPONSE_USER_ID_FIELD.default_value = 0
LOGINRESPONSE_USER_ID_FIELD.type = 5
LOGINRESPONSE_USER_ID_FIELD.cpp_type = 1

LOGINRESPONSE_PLAYER_FIELD.name = "player"
LOGINRESPONSE_PLAYER_FIELD.full_name = ".my_project.LoginResponse.player"
LOGINRESPONSE_PLAYER_FIELD.number = 11
LOGINRESPONSE_PLAYER_FIELD.index = 1
LOGINRESPONSE_PLAYER_FIELD.label = 1
LOGINRESPONSE_PLAYER_FIELD.has_default_value = false
LOGINRESPONSE_PLAYER_FIELD.default_value = nil
LOGINRESPONSE_PLAYER_FIELD.message_type = COMMON_BASE_PB._PLAYER
LOGINRESPONSE_PLAYER_FIELD.type = 11
LOGINRESPONSE_PLAYER_FIELD.cpp_type = 10

LOGINRESPONSE.name = "LoginResponse"
LOGINRESPONSE.full_name = ".my_project.LoginResponse"
LOGINRESPONSE.nested_types = {}
LOGINRESPONSE.enum_types = {}
LOGINRESPONSE.fields = {LOGINRESPONSE_USER_ID_FIELD, LOGINRESPONSE_PLAYER_FIELD}
LOGINRESPONSE.is_extendable = false
LOGINRESPONSE.extensions = {}
CREATECHARACTERREQUEST_USER_ID_FIELD.name = "user_id"
CREATECHARACTERREQUEST_USER_ID_FIELD.full_name = ".my_project.CreateCharacterRequest.user_id"
CREATECHARACTERREQUEST_USER_ID_FIELD.number = 1
CREATECHARACTERREQUEST_USER_ID_FIELD.index = 0
CREATECHARACTERREQUEST_USER_ID_FIELD.label = 2
CREATECHARACTERREQUEST_USER_ID_FIELD.has_default_value = false
CREATECHARACTERREQUEST_USER_ID_FIELD.default_value = 0
CREATECHARACTERREQUEST_USER_ID_FIELD.type = 5
CREATECHARACTERREQUEST_USER_ID_FIELD.cpp_type = 1

CREATECHARACTERREQUEST_PLAYER_NAME_FIELD.name = "player_name"
CREATECHARACTERREQUEST_PLAYER_NAME_FIELD.full_name = ".my_project.CreateCharacterRequest.player_name"
CREATECHARACTERREQUEST_PLAYER_NAME_FIELD.number = 2
CREATECHARACTERREQUEST_PLAYER_NAME_FIELD.index = 1
CREATECHARACTERREQUEST_PLAYER_NAME_FIELD.label = 2
CREATECHARACTERREQUEST_PLAYER_NAME_FIELD.has_default_value = false
CREATECHARACTERREQUEST_PLAYER_NAME_FIELD.default_value = ""
CREATECHARACTERREQUEST_PLAYER_NAME_FIELD.type = 9
CREATECHARACTERREQUEST_PLAYER_NAME_FIELD.cpp_type = 9

CREATECHARACTERREQUEST.name = "CreateCharacterRequest"
CREATECHARACTERREQUEST.full_name = ".my_project.CreateCharacterRequest"
CREATECHARACTERREQUEST.nested_types = {}
CREATECHARACTERREQUEST.enum_types = {}
CREATECHARACTERREQUEST.fields = {CREATECHARACTERREQUEST_USER_ID_FIELD, CREATECHARACTERREQUEST_PLAYER_NAME_FIELD}
CREATECHARACTERREQUEST.is_extendable = false
CREATECHARACTERREQUEST.extensions = {}
CREATECHARACTERRESPONSE_USER_ID_FIELD.name = "user_id"
CREATECHARACTERRESPONSE_USER_ID_FIELD.full_name = ".my_project.CreateCharacterResponse.user_id"
CREATECHARACTERRESPONSE_USER_ID_FIELD.number = 1
CREATECHARACTERRESPONSE_USER_ID_FIELD.index = 0
CREATECHARACTERRESPONSE_USER_ID_FIELD.label = 2
CREATECHARACTERRESPONSE_USER_ID_FIELD.has_default_value = false
CREATECHARACTERRESPONSE_USER_ID_FIELD.default_value = 0
CREATECHARACTERRESPONSE_USER_ID_FIELD.type = 5
CREATECHARACTERRESPONSE_USER_ID_FIELD.cpp_type = 1

CREATECHARACTERRESPONSE.name = "CreateCharacterResponse"
CREATECHARACTERRESPONSE.full_name = ".my_project.CreateCharacterResponse"
CREATECHARACTERRESPONSE.nested_types = {}
CREATECHARACTERRESPONSE.enum_types = {}
CREATECHARACTERRESPONSE.fields = {CREATECHARACTERRESPONSE_USER_ID_FIELD}
CREATECHARACTERRESPONSE.is_extendable = false
CREATECHARACTERRESPONSE.extensions = {}
LOGOUTRESPONSE_USER_ID_FIELD.name = "user_id"
LOGOUTRESPONSE_USER_ID_FIELD.full_name = ".my_project.LogoutResponse.user_id"
LOGOUTRESPONSE_USER_ID_FIELD.number = 1
LOGOUTRESPONSE_USER_ID_FIELD.index = 0
LOGOUTRESPONSE_USER_ID_FIELD.label = 2
LOGOUTRESPONSE_USER_ID_FIELD.has_default_value = false
LOGOUTRESPONSE_USER_ID_FIELD.default_value = 0
LOGOUTRESPONSE_USER_ID_FIELD.type = 5
LOGOUTRESPONSE_USER_ID_FIELD.cpp_type = 1

LOGOUTRESPONSE.name = "LogoutResponse"
LOGOUTRESPONSE.full_name = ".my_project.LogoutResponse"
LOGOUTRESPONSE.nested_types = {}
LOGOUTRESPONSE.enum_types = {}
LOGOUTRESPONSE.fields = {LOGOUTRESPONSE_USER_ID_FIELD}
LOGOUTRESPONSE.is_extendable = false
LOGOUTRESPONSE.extensions = {}
HEARTBEAT_PLAYER_ID_FIELD.name = "player_id"
HEARTBEAT_PLAYER_ID_FIELD.full_name = ".my_project.HeartBeat.player_id"
HEARTBEAT_PLAYER_ID_FIELD.number = 1
HEARTBEAT_PLAYER_ID_FIELD.index = 0
HEARTBEAT_PLAYER_ID_FIELD.label = 2
HEARTBEAT_PLAYER_ID_FIELD.has_default_value = false
HEARTBEAT_PLAYER_ID_FIELD.default_value = ""
HEARTBEAT_PLAYER_ID_FIELD.type = 9
HEARTBEAT_PLAYER_ID_FIELD.cpp_type = 9

HEARTBEAT.name = "HeartBeat"
HEARTBEAT.full_name = ".my_project.HeartBeat"
HEARTBEAT.nested_types = {}
HEARTBEAT.enum_types = {}
HEARTBEAT.fields = {HEARTBEAT_PLAYER_ID_FIELD}
HEARTBEAT.is_extendable = false
HEARTBEAT.extensions = {}

CreateCharacterRequest = protobuf.Message(CREATECHARACTERREQUEST)
CreateCharacterResponse = protobuf.Message(CREATECHARACTERRESPONSE)
HeartBeat = protobuf.Message(HEARTBEAT)
LoginRequest = protobuf.Message(LOGINREQUEST)
LoginResponse = protobuf.Message(LOGINRESPONSE)
LogoutResponse = protobuf.Message(LOGOUTRESPONSE)
login_pb.CREATECHARACTERREQUEST = CREATECHARACTERREQUEST
login_pb.CREATECHARACTERRESPONSE = CREATECHARACTERRESPONSE
login_pb.CreateCharacterRequest = CreateCharacterRequest
login_pb.CreateCharacterResponse = CreateCharacterResponse
login_pb.HEARTBEAT = HEARTBEAT
login_pb.HeartBeat = HeartBeat
login_pb.LOGINREQUEST = LOGINREQUEST
login_pb.LOGINRESPONSE = LOGINRESPONSE
login_pb.LOGOUTRESPONSE = LOGOUTRESPONSE
login_pb.LoginRequest = LoginRequest
login_pb.LoginResponse = LoginResponse
login_pb.LogoutResponse = LogoutResponse


return login_pb
